[package]
name = "SCloudDNS"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = "0.26"
strum_macros = "0.26"

rand = "0.9.2"
anyhow = "1.0.100"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

tempfile = "3.23.0"

nix = { version = "0.31.1", features = ["process", "user"] }
libc = "0.2.180"
winapi = "0.3.9"

uuid = { version = "1.20.0", features = ["v4", "serde"] }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time"] }
tokio-amqp = "2.0"

lapin = { version = "=3.7.2", features = ["rustls"] }

reactor-trait = "=2.7.0"
tokio-reactor-trait = "=2.7.0"

executor-trait = "=2.1.0"
tokio-executor-trait = "=2.1.3"


futures-util = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "winbase"] }