[package]
name = "SCloudDNS"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = "0.26"
strum_macros = "0.26"
rand = "0.9.2"
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"